---
name: "YouTube Metadata"
guid: "b4b4353e-dc57-4398-82c1-de9079e7146a"
version: "1.0.3.2"
targetAbi: "10.9.1.0"
owner: "ankenyr"
overview: "YouTube metadata provider"
description: "Provides YouTube metadata from the YouTube API and Youtube-dl metadata files."
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.YoutubeMetadata.dll"
- "NYoutubeDLP.dll"
- "System.IO.Abstractions.dll"
changelog: >
  changelog
