---
name: "YouTube Metadata"
guid: "b4b4353e-dc57-4398-82c1-de9079e7146a"
version: "1.0.3.13"
targetAbi: "10.9.1.0"
framework: "net9.0"
owner: "ankenyr"
overview: "YouTube metadata provider"
description: "Provides YouTube metadata from the YouTube API and Youtube-dl metadata files."
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.YoutubeMetadata.dll"
- "NYoutubeDLP.dll"
- "System.IO.Abstractions.dll"
changelog: >
  #120 tcely: Match a specific YouTube ID for thumbnail
  #143 mcronce: Jellyfin 10.11 support
