version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - 8096:8096
    command: sleep infinity
    volumes:
      - ../:/workspaces/youtube-metadata:cached